### ISSUE TITLE
PHP7 Issues?

### ISSUE THREAD

**Issue by Radau** [bugsnag/bugsnag-wordpress#13]
Not sure if this is related to PHP7 but I'm getting the following error very frequently:

**PHP Fatal Error** POST /wp-cron.php
```
PHP Fatal Error Uncaught TypeError: Argument 3 passed to Bugsnag_Error::fromPHPException() must be an instance of Exception, instance of Error given, called in /app/htdocs/assets/plugins/bugsnag/bugsnag-php/Client.php on line 360 and defined in /app/htdocs/assets/plugins/bugsnag/bugsnag-php/Error.php:31
Stack trace:
#0 /app/htdocs/assets/plugins/bugsnag/bugsnag-php/Client.php(360): Bugsnag_Error::fromPHPException(Object(Bugsnag_Configuration), Object(Bugsnag_Diagnostics), Object(Error))
#1 [internal function]: Bugsnag_Client->exceptionHandler(Object(Error))
#2 {main}
  thrown 
    assets/plugins/bugsnag/bugsnag-php/Error.php:31 [unknown]
```

Only happening in staging and production (both are 1:1 replicas) but not VVV. staging/production are `7.0.3`, my VVV install is `5.5.9`. Seems similar to bugsnag/bugsnag-php#102

**Comment by GrahamCampbell** [comment]
Thanks for the report. This is due to a bad version constraint in our composer file. I've fixed this now. It'll be fixed in our next tag.
