### ISSUE TITLE
Wordpress Plugin Directory version is out of date

### ISSUE THREAD

**Issue by iamtommcc** [bugsnag/bugsnag-wordpress#14]
Hi there wonderful people,

After running into issue #13, I noticed the [WordPress repo](https://wordpress.org/plugins/bugsnag) for this plugin is still stuck on 1.1.2.

It's a real "gotcha", as the official installation instructions still recommend using this outdated version which doesn't work on all PHP7 installations. I had to download and rebuild from the latest commit to get things working again.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch @iamtommcc.

---

Ping @kattrali, @loopj.

**Comment by lots0logs** [comment]
@GrahamCampbell @kattrali @loopj Status update?

**Comment by kattrali** [comment]
I’ve cut a GH release of 1.3.0, having a bit of trouble with the WP directory.

**Comment by youanden** [comment]
@kattrali Status update? Can I help in any way? I have a wordpress install on Envoyer and would prefer not to add bugsnag-wordpress directly into my git repository as a dependency to resolve issue #13 .

**Comment by kattrali** [comment]
Got this sorted. Latest on Wordpress is now 1.3.0.
