### ISSUE TITLE
$bugsnagWordpress variable not available on CLI scripts

### ISSUE THREAD

**Issue by nviitala** [bugsnag/bugsnag-wordpress#23]
### Expected behavior
$bugsnagWordpress to be Bugsnag_Wordpress object

### Observed behavior
$bugsnagWordpress is null

### Steps to reproduce
Run wp-cli's eval-file ( https://developer.wordpress.org/cli/commands/eval-file/ ) to file which has a $bugsnagWordpress variable

### Version
1.3.0

### Additional information
Suggested fix:
Add: `global $bugsnagWordpress;`
before: `$bugsnagWordpress = new Bugsnag_Wordpress();`
On bugsnag.php

**Comment by Cawllec** [comment]
Hi @nviitala, thanks for the feedback, sorry it's taken so long to get to this.
We'll have a look at making that change.

**Comment by tomlongridge** [comment]
This will be fixed in #40
