### ISSUE TITLE
Set notification stages

### ISSUE THREAD

**Issue by tillkruss** [bugsnag/bugsnag-wordpress#24]
I can't find any way to call the `setNotifyReleaseStages()`. How can I configure that with WordPress?

**Comment by Cawllec** [comment]
Hi @tillkruss, you need to set it on your `$bugsnagWordpress` client object, as demonstrated [here](https://docs.bugsnag.com/platforms/php/wordpress/configuration-options/#setnotifyreleasestages)

**Comment by tillkruss** [comment]
But how? Using a MU-Plugin, or where exactly?

**Comment by Cawllec** [comment]
Hi @tillkruss, sorry it's taken me a while to get back to this.  You should be able to set it anywhere after `$bugsnagWordpress` is initialised, such as in `functions.php` in your theme.

**Comment by tillkruss** [comment]
Thanks!
