### ISSUE TITLE
Consider WP Enforcer

### ISSUE THREAD

**Issue by bhubbard** [bugsnag/bugsnag-wordpress#26]
Hey guys, I would like you to consider adding WP Enforcer to help enforce WordPress standards for this plugin. You can check it out here:

https://github.com/stevegrunwell/wp-enforcer

https://stevegrunwell.com/blog/wp-enforcer/

**Comment by Cawllec** [comment]
Hi @bhubbard, thanks for letting us know about that!  I'm going to close this Issue, but move the conversation to your PR, as we could do with some CI/QA on here.

**Comment by Cawllec** [comment]
[The PR in question](https://github.com/bugsnag/bugsnag-wordpress/pull/28)
