### ISSUE TITLE
Enable Display_errors?

### ISSUE THREAD

**Issue by Luc45** [bugsnag/bugsnag-wordpress#31]
### Expected behavior
I would like to enable display_errors

### Observed behavior
dispaly_errors is turned off by Bugnsag plugin

### Steps to reproduce
None

### Version
1.3.0

### Additional information
I had to go deep to understand where the display_error was being turned off. I used ini_get('display_errors') on wp-settings.php where it loads the plugins and found out that Bugsnag disables it. I couldn't find in the plugin where to turn it on.

**Comment by Luc45** [comment]
Sorry, it was Query Monitor that was disabling the display_error. Closing issue.

**Comment by simplenotezy** [comment]
@Luc45 - can you elaborate a bit? I have same difficulities here #41

**Comment by Luc45** [comment]
@simplenotezy Sorry, this was too long ago and I don't remember what I did
