### ISSUE TITLE
Update the wordpress.org version

### ISSUE THREAD

**Issue by Brugman** [bugsnag/bugsnag-wordpress#32]
Bugsnag helped me find that `screen_icon()` is deprecated. My version is 1.3.0, this repo has version 1.3.0, so I wanted to PR it, but then I see that it's already been fixed ([commit](https://github.com/bugsnag/bugsnag-wordpress/commit/c66e2dc77bb3c9f0ad9196e21a5a246e16a6ef58))

Soo... this 1.3.0 does not match the wordpress.org 1.3.0. And this being a WP plugin, I'd say it's pretty important to get the latest version up to wordpress.org. The "wp repo" version already has a warning on it for not being updated for a long time so it's about time.

**Comment by bengourley** [comment]
Hi @Brugman I've just created a new version with the `screen_icon()` fix and published it. The version should appear on Worpress.org shortly, but it is already avaliable on the [releases](https://github.com/bugsnag/bugsnag-wordpress/releases) page here if you want to install it that way.

**Comment by Brugman** [comment]
Thanks @bengourley! The warning is still on wp.org because the Tested tag is on 4.15, if you could update that (I assume it runs fine on the latest version, I know I'm using it), I think that would give visitors more confidence in Bugsnag.

**Comment by bengourley** [comment]
Thanks @Brugman – I tried to update that yesterday, to no avail. Managed to do it this morning. Cheers!
