### ISSUE TITLE
Update Release Stage

### ISSUE THREAD

**Issue by bhubbard** [bugsnag/bugsnag-wordpress#50]
WordPress now has a default function called `wp_get_environment_type`, this should be used instead of `WP_ENV` for the release stage. 

https://developer.wordpress.org/reference/functions/wp_get_environment_type/

**Comment by johnkiely1** [comment]
Hi @bhubbard,

Thanks for this and the associated PR. We will review when priorities allow.

**Comment by mattdyoung** [comment]
Now released in [v1.6.0](https://github.com/bugsnag/bugsnag-wordpress/releases/tag/v1.6.0)
