### ISSUE TITLE
Support WordPress Coding Standards

### ISSUE THREAD

**Issue by bhubbard** [bugsnag/bugsnag-wordpress#54]
As this is a WordPress plugin, I would like to see it move into a direction to better support [WordPress Coding Standards](https://github.com/WordPress/WordPress-Coding-Standards).

**Comment by johnkiely1** [comment]
Hi @bhubbard ,

Thanks for the PR on this, this seems like a good suggestion. We will review as soon as we can.

**Comment by imjoehaines** [comment]
Closing for the reasons mentioned on the PR: https://github.com/bugsnag/bugsnag-wordpress/pull/55
