### ISSUE TITLE
integrate Mangopay api to wordpress website

### ISSUE THREAD

**Issue by rota90** [bugsnag/bugsnag-wordpress#8]
Hi,
I need to integrate Mangopay API into wordpress site.
I am new to wordpress and mangopay too.
Could you please help me?
Thanks in advance

**Comment by ConradIrwin** [comment]
Hey @rota90, unfortunately we are not wordpress experts either :). The best thing to do would be to search for "wordpress hosting with mangopay" on google and see if there's anyone who offers this as a service.

Good luck!
